spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/iloveweilai/spring-cloud-config-demo.git
          #username: 
          #password:
          search-paths: SC-BOOK-CONFIG
  application:
    name: myr-config-git
server:
  port: 9090
